// Copyright 2024 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ==============================================================================

#ifndef BARKOUR_ROBOT_FIRMWARE_BARKOUR_DRIVERS_STM32H7_HAL_FOC_COMMUTATION_TEST_DATA_H_
#define BARKOUR_ROBOT_FIRMWARE_BARKOUR_DRIVERS_STM32H7_HAL_FOC_COMMUTATION_TEST_DATA_H_

// This file is auto generated by the matlab/octave script
// ../scripts/testdata/FocMathTestDataGen.m

// This file is included in the realtime_foc_tests.cc
// and used in the unit tests for the foc functions.

#define NUM_COM_TESTS 24
#define FOC_COM_TEST_DATA_INIT                                                 \
  {                                                                            \
        /* 0.000000 */                                                         \
        {{0, 33363, 32470},                                                    \
         FocInterface::FocState(+1.000000, -0.500000, -0.500000, +0.531250,    \
                                +0.468750, +0.468750, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +0.000000,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 0.263894 */                                                         \
        {{131, 32345, 33343},                                                  \
         FocInterface::FocState(+0.965382, -0.256795, -0.708586, +0.534874,    \
                                +0.483950, +0.465126, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +0.263894,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 0.527788 */                                                         \
        {{262, 33282, 32770},                                                  \
         FocInterface::FocState(+0.863923, +0.004189, -0.868112, +0.536084,    \
                                +0.500262, +0.463916, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +0.527788,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 0.791681 */                                                         \
        {{393, 33186, 32925},                                                  \
         FocInterface::FocState(+0.702650, +0.264883, -0.967533, +0.534795,    \
                                +0.516555, +0.465205, -0.000000, +1.000000,    \
                                +0.000000, +1.000000, +0.791681,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 1.055575 */                                                         \
        {{524, 33061, 33070},                                                  \
         FocInterface::FocState(+0.492727, +0.507238, -0.999965, +0.530795,    \
                                +0.531400, +0.468600, -0.000000, +1.000000,    \
                                +0.000000, +1.000000, +1.055575,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 1.319469 */                                                         \
        {{655, 32916, 33193},                                                  \
         FocInterface::FocState(+0.248690, +0.714473, -0.963163, +0.515543,    \
                                +0.534951, +0.465049, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +1.319469,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 1.583363 */                                                         \
        {{786, 32760, 33287},                                                  \
         FocInterface::FocState(-0.012566, +0.872240, -0.859674, +0.499215,    \
                                +0.536082, +0.463918, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +1.583363,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 1.847256 */                                                         \
        {{917, 32605, 33345},                                                  \
         FocInterface::FocState(-0.272952, +0.969616, -0.696664, +0.482941,    \
                                +0.534714, +0.465286, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +1.847256,               \
                                PhaseSampleSelection::kAB)},                   \
        /* 2.111150 */                                                         \
        {{1049, 32461, 33363},                                                 \
         FocInterface::FocState(-0.514440, +0.999860, -0.485420, +0.468452,    \
                                +0.531548, +0.469661, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +2.111150,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 2.375044 */                                                         \
        {{1180, 32624, 33340},                                                 \
         FocInterface::FocState(-0.720309, +0.960876, -0.240567, +0.464975,    \
                                +0.535025, +0.484965, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +2.375044,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 2.638938 */                                                         \
        {{1311, 32780, 33277},                                                 \
         FocInterface::FocState(-0.876307, +0.855364, +0.020942, +0.463924,    \
                                +0.536076, +0.501309, -0.000000, +1.000000,    \
                                +0.000000, +1.000000, +2.638938,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 2.902832 */                                                         \
        {{1442, 32935, 33179},                                                 \
         FocInterface::FocState(-0.971632, +0.690630, +0.281002, +0.465370,    \
                                +0.534630, +0.517563, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +2.902832,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 3.166725 */                                                         \
        {{1573, 33078, 33052},                                                 \
         FocInterface::FocState(-0.999684, +0.478079, +0.521605, +0.468306,    \
                                +0.529880, +0.531694, -0.000000, +1.000000,    \
                                +0.000000, +1.000000, +3.166725,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 3.430619 */                                                         \
        {{1704, 33200, 32906},                                                 \
         FocInterface::FocState(-0.958522, +0.232427, +0.726095, +0.464904,    \
                                +0.514527, +0.535096, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +3.430619,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 3.694513 */                                                         \
        {{1835, 33292, 32750},                                                 \
         FocInterface::FocState(-0.850994, -0.029317, +0.880312, +0.463931,    \
                                +0.498168, +0.536069, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +3.694513,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 3.958407 */                                                         \
        {{1966, 33348, 32595},                                                 \
         FocInterface::FocState(-0.684547, -0.289032, +0.973579, +0.465456,    \
                                +0.481936, +0.534544, -0.000000, +1.000000,    \
                                +0.000000, +1.000000, +3.958407,               \
                                PhaseSampleSelection::kBC)},                   \
        /* 4.222301 */                                                         \
        {{2097, 33363, 32452},                                                 \
         FocInterface::FocState(-0.470704, -0.528735, +0.999439, +0.470581,    \
                                +0.468163, +0.531837, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +4.222301,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 4.486194 */                                                         \
        {{2228, 33337, 32634},                                                 \
         FocInterface::FocState(-0.224271, -0.731830, +0.956100, +0.485983,    \
                                +0.464835, +0.535165, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +4.486194,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 4.750088 */                                                         \
        {{2359, 33272, 32790},                                                 \
         FocInterface::FocState(+0.037690, -0.884255, +0.846565, +0.502356,    \
                                +0.463941, +0.536059, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +4.750088,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 5.013982 */                                                         \
        {{2490, 33172, 32944},                                                 \
         FocInterface::FocState(+0.297042, -0.975458, +0.678416, +0.518565,    \
                                +0.465544, +0.534456, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +5.013982,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 5.277876 */                                                         \
        {{2621, 33044, 33087},                                                 \
         FocInterface::FocState(+0.535827, -0.999123, +0.463296, +0.531978,    \
                                +0.468022, +0.528956, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +5.277876,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 5.541769 */                                                         \
        {{2752, 32896, 33207},                                                 \
         FocInterface::FocState(+0.737513, -0.953612, +0.216099, +0.535232,    \
                                +0.464768, +0.513506, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +5.541769,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 5.805663 */                                                         \
        {{2884, 32740, 33297},                                                 \
         FocInterface::FocState(+0.888136, -0.842076, -0.046060, +0.536046,    \
                                +0.463954, +0.497121, +0.000000, +1.000000,    \
                                +0.000000, +1.000000, +5.805663,               \
                                PhaseSampleSelection::kAC)},                   \
        /* 6.069557 */                                                         \
        {{3015, 32586, 33350},                                                 \
          FocInterface::FocState(+0.977268, -0.672238, -0.305031, +0.534365,   \
                                 +0.465635, +0.480936, -0.000000, +1.000000,   \
                                 +0.000000, +1.000000, +6.069557,              \
                                 PhaseSampleSelection::kAC)                    \
    }                                                                          \
  }

#endif  // BARKOUR_ROBOT_FIRMWARE_BARKOUR_DRIVERS_STM32H7_HAL_FOC_COMMUTATION_TEST_DATA_H_
